### ISSUE TITLE
Capturing does not work

### ISSUE THREAD

**Issue by boristian** [mtth/layer2#1]
Hello,

at first i might want to thank you for your work.

I was trying to live-capture some ethernet frames from the ethernet adapter attached to my MBP and log them, but i got nothing. Here is the code i've used:

``` javascript
var layer2 = require('layer2');

var capture = new layer2.capture.Live('en4');
var decoder = new layer2.Decoder({linkType: 'EN10MB'});

capture           // Stream of buffers (frames' raw bytes).
    .pipe(decoder)  // Stream of objects (decoded frames).
    .on('data', function (frame) { console.log(JSON.stringify(frame)); });
```

What did i do wrong?

Greets and thanks in advance,
Christian

**Comment by mtth** [comment]
Hey Christian. What happens when you add `{assumeValid: true}` to the decoder options?

**Comment by boristian** [comment]
Thanks, that worked.
