### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by dcousens** [mtth/layer2#3]
In trying to install this package,  I got the following error:

```
../src/cpp/pcap_wrapper.h:50:54: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> to_savefile(const v8::Arguments& args);
```

Sorry I couldn't check out the cause of this myself.

**Comment by mtth** [comment]
What version of `node` are you running? What was the install command you ran?

**Comment by dcousens** [comment]
Node 0.12

npm install level2

**Comment by mtth** [comment]
Can you try `npm install layer2`? (`level2` is deprecated.)

**Comment by dcousens** [comment]
@mtth could you please deprecate https://www.npmjs.com/package/level2 on npm then?

**Comment by mtth** [comment]
Done. Did installing `layer2` work?

**Comment by dcousens** [comment]
@mtth that it did, thanks for the help :)
