### ISSUE TITLE
Is `dat` dir packed on a purpose?

### ISSUE THREAD

**Issue by ChALkeR** [mtth/layer2#4]
_Disclaimer: I do not use the package, this was found during automated npm packages downloading._

Your current package size is 20 MiB packed, 479 MiB unpacked. 475 MiB of that are inside the `dat` dir and that space is taken mostly by `*.pcap` files. I suspect that this probably got packed to the release by mistake.

If you don't want to pack that directory, add it to the `.gitignore` and/or `.npmingore`.

**Comment by ChALkeR** [comment]
The same for the `level2` package.
The same for the `dot11` package.

**Comment by ChALkeR** [comment]
Btw, `*.pcap` files could contain sensitive data.

**Comment by mtth** [comment]
Thanks for pointing this out! Total size should now be less than 1MB (I wasn't aware `npm publish` didn't pick up the global `.gitignore`). To your other points, both `level2` and `dot11` are deprecated, and the `.pcap` files were all public data (mostly from [here](https://wiki.wireshark.org/SampleCaptures)).

**Comment by ChALkeR** [comment]
`level2` and `dot11` have no dependants, so I believe that you can safely unpublish those if you wish.

http://registry.npmjs.org/-/_view/dependedUpon?group_level=3&startkey=%5B%22level2%22%5D&endkey=%5B%22level2%22%2C%7B%7D%5D&skip=0&limit=1000
http://registry.npmjs.org/-/_view/dependedUpon?group_level=3&startkey=%5B%22dot11%22%5D&endkey=%5B%22dot11%22%2C%7B%7D%5D&skip=0&limit=1000

**Comment by ChALkeR** [comment]
`dot11` is still affected.

**Comment by mtth** [comment]
Apologies, should be fixed now.

**Comment by ChALkeR** [comment]
Thanks.

Just to be clear: I'm not associated with npmjs.org in any way.

I was just downloading packages for quick and dirty code analysis (for example, to see how many packages use deprecated API), and I decided to file bugs agaist the packages that have huge sizes by what I think is a mistake.

I have seen an 1.1 GiB (unpacked) coredump and a 3.1 GiB (unpacked) MongoDB data dir… ;-)
